default: &default
  default: &default
    adapter: postgresql
    encoding: unicode
    username: postgres
    password: 123456
    host: localhost
    pool: 5

development:
  <<: *default
  database: hakawy_development

test:
  <<: *default
  database: hakawy_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
